feat/arithmetic operators closes #6
manugentile/manugentile.github.io pull request #17
Opened 2024-03-17 00:04 UTC by scriptswhisper

2024-03-17 09:09 UTC, manugentile requested changes

2024-03-17 09:09 UTC, manugentile commented on courses/sql/3_operators/sql-arithmetic-operators.md
> +## Arithmetic
I'd remove the Overview code from arithmetic one

2024-03-17 14:46 UTC, scriptswhisper commented on courses/sql/3_operators/sql-arithmetic-operators.md
> +## Arithmetic
Sorry, I don't get it @manugentile, what do you want to change?

2024-03-18 09:36 UTC, manugentile commented on courses/sql/3_operators/sql-arithmetic-operators.md
> +## Arithmetic
@scriptswhisper You added the overview info, like Types of SQL operators, comparison (etc) into the arithmetic operator file

2024-03-18 10:09 UTC, scriptswhisper commented on courses/sql/3_operators/sql-arithmetic-operators.md
> +## Arithmetic
Updated, thanks for the detailed info @manugentile

2024-03-18 15:01 UTC, merged